name: deploy-to-production

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy-to-staging:
    uses: ./build_and_deploy.yml
    with:
      hostname: https://help.sumologic.com
      environment: production
